### ISSUE TITLE
Micropython

### ISSUE THREAD

**Issue by klint-k** [nstansby/rpi-rotary-encoder-python#4]
How would this be converted over to Micropython?

**Comment by nstansby** [comment]
I've never used Micropython, but it there are only 6 lines of code here that interact with the hardware; the rest is just plain old Python and should work just fine.  You'd need to adapt those lines (basically anywhere you see `GPIO.` in the code) to however you do the same things in Micropython.  [This](https://docs.micropython.org/en/latest/esp8266/tutorial/pins.html#) page seems to cover what you'd need.
