### ISSUE TITLE
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)

### ISSUE THREAD

**Issue by BluCobalt** [nstansby/rpi-rotary-encoder-python#5]
Using this leads to the error `RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)` at line 16.
This can be fixed by adding GPIO.setmode(GPIO.BCM) before the GPIO.setup() calls, shown here.
![image](https://user-images.githubusercontent.com/37788256/118915764-7fbacb80-b8e2-11eb-823e-607daefd6773.png)

**Comment by nstansby** [comment]
I think this type of board/environment configuration should be done by the top-level script that's using this code, rather than in this code itself.  Unless there's some reason why that wouldn't work, I'm not going to add it to this package.
